# Generated by Django 6.1 on 2026-08-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_university_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
