# Generated by Django 6.1 on 2026-09-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_logbooktemplate_logbookfield_weeklylogbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookfield',
            name='choices',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
