# Generated by Django 6.1 on 2026-09-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_logbookfield_choices'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='logbookentry',
            name='unique_logbook_entry_per_day',
        ),
        migrations.RemoveField(
            model_name='logbookfield',
            name='template',
        ),
        migrations.RemoveField(
            model_name='logbooktemplate',
            name='university',
        ),
        migrations.RemoveConstraint(
            model_name='weeklylogbook',
            name='unique_student_weekly_logbook',
        ),
        migrations.RemoveField(
            model_name='logbookentry',
            name='logbook',
        ),
        migrations.DeleteModel(
            name='LogbookField',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='student',
        ),
        migrations.RemoveField(
            model_name='weeklylogbook',
            name='template',
        ),
        migrations.DeleteModel(
            name='LogbookEntry',
        ),
        migrations.DeleteModel(
            name='LogbookTemplate',
        ),
        migrations.DeleteModel(
            name='WeeklyLogbook',
        ),
    ]
