# Generated by Django 6.1 on 2026-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
        ('students', '0008_university_latitude_university_longitude'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'internship'), name='unique_student_internship_application'),
        ),
    ]
