# Generated by Django 6.1.1 on 2026-10-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_application_unique_student_internship_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
