# Generated by Django 6.1 on 2026-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_legaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='Your Internship Journey Starts Here', max_length=150)),
                ('hero_title', models.CharField(default='Connecting Students, Universities & Employers in One Platform', max_length=300)),
                ('hero_description', models.TextField(default='Discover internship opportunities, manage student placements, and connect universities with employers — all in one place.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('hero_primary_button', models.CharField(default='Find an Internship', max_length=100)),
                ('hero_secondary_button', models.CharField(default='Join Now', max_length=100)),
                ('about_badge', models.CharField(default='ABOUT US', max_length=100)),
                ('about_title', models.CharField(default='About InternConnect', max_length=200)),
                ('about_description', models.TextField(default='InternConnect is a digital platform that bridges the gap between students, universities and employers.')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField(default='Empower young talent through meaningful internships.')),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_text', models.TextField(default='A future where every student has access to quality internship opportunities.')),
                ('values_title', models.CharField(default='Our Values', max_length=100)),
                ('values_text', models.TextField(default='Integrity, Innovation, Collaboration, Impact.')),
                ('cta_title', models.CharField(default='Ready to be part of the Internship Network?', max_length=250)),
                ('cta_description', models.TextField(default='Join thousands of students, universities and companies already on InternConnect.')),
                ('footer_description', models.TextField(blank=True, default='Connect students, universities and employers.')),
                ('newsletter_title', models.CharField(default='Subscribe to Our Newsletter', max_length=150)),
                ('newsletter_description', models.TextField(default='Get the latest updates and opportunities.')),
                ('copyright_text', models.CharField(default='© 2025 InternConnect. All rights reserved.', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Settings',
                'verbose_name_plural': 'Landing Page Settings',
            },
        ),
    ]
