# Generated by Django 6.1.1 on 2026-10-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_landingpagesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_university_dashboard', 'Can view university dashboard')]},
        ),
    ]
