# Generated by Django 6.1.1 on 2026-10-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_university_dashboard', 'Can view university dashboard'), ('view_company_dashboard', 'Can view company dashboard')]},
        ),
    ]
