# Generated by Django 6.1 on 2026-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='Your Internship Journey Starts Here', max_length=150)),
                ('hero_title', models.CharField(default='Connecting Students, Universities & Employers in One Platform', max_length=300)),
                ('hero_description', models.TextField(default='Discover internship opportunities, manage student placements, and connect universities with employers — all in one place.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('hero_primary_button', models.CharField(default='Find an Internship', max_length=100)),
                ('hero_secondary_button', models.CharField(default='Join Now', max_length=100)),
                ('about_badge', models.CharField(default='ABOUT US', max_length=100)),
                ('about_title', models.CharField(default='About InternConnect', max_length=200)),
                ('about_description', models.TextField(default='InternConnect is a digital platform that bridges the gap between students, universities and employers.')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField(default='Empower young talent through meaningful internships.')),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_text', models.TextField(default='A future where every student has access to quality internship opportunities.')),
                ('values_title', models.CharField(default='Our Values', max_length=100)),
                ('values_text', models.TextField(default='Integrity, Innovation, Collaboration, Impact.')),
                ('cta_title', models.CharField(default='Ready to be part of the Internship Network?', max_length=250)),
                ('cta_description', models.TextField(default='Join thousands of students, universities and companies already on InternConnect.')),
                ('footer_description', models.TextField(blank=True, default='Connect students, universities and employers.')),
                ('newsletter_title', models.CharField(default='Subscribe to Our Newsletter', max_length=150)),
                ('newsletter_description', models.TextField(default='Get the latest updates and opportunities.')),
                ('copyright_text', models.CharField(default='© 2025 InternConnect. All rights reserved.', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Settings',
                'verbose_name_plural': 'Landing Page Settings',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='about_video_duration',
            field=models.CharField(default='2:30', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='about_video_text',
            field=models.CharField(default='Watch Our Story', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='about_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='cta_icon',
            field=models.CharField(default='🎓', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='faq_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='features_badge',
            field=models.CharField(default='OUR FEATURES', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='features_description',
            field=models.TextField(default='Powerful features designed for students, universities and companies.'),
        ),
        migrations.AddField(
            model_name='company',
            name='features_title',
            field=models.CharField(default='Everything You Need for a Successful Internship', max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='get_started_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='help_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='hero_primary_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='hero_secondary_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='login_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_first',
            field=models.CharField(default='Intern', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_second',
            field=models.CharField(default='Connect', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='network_badge',
            field=models.CharField(default='EXPLORE OUR NETWORK', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='network_description',
            field=models.TextField(default='Explore the locations of universities and companies participating in our platform.'),
        ),
        migrations.AddField(
            model_name='company',
            name='network_title',
            field=models.CharField(default='Universities & Companies Across Uganda', max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='newsletter_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='privacy_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='site_name',
            field=models.CharField(default='InternConnect', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='student_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(default='Connect. Intern. Grow.', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='terms_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='university_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='x_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='landing/'),
        ),
    ]
