# Generated by Django 6.1 on 2026-09-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_landingpagesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesettings',
            name='about_video_duration',
            field=models.CharField(default='2:30', max_length=20),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='about_video_text',
            field=models.CharField(default='Watch Our Story', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='about_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='company_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='cta_icon',
            field=models.CharField(default='🎓', max_length=20),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='faq_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='features_badge',
            field=models.CharField(default='OUR FEATURES', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='features_description',
            field=models.TextField(default='Powerful features designed for students, universities and companies.'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='features_title',
            field=models.CharField(default='Everything You Need for a Successful Internship', max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='get_started_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='help_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='hero_primary_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='hero_secondary_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='login_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='landing/'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='logo_first',
            field=models.CharField(default='Intern', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='logo_second',
            field=models.CharField(default='Connect', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='network_badge',
            field=models.CharField(default='EXPLORE OUR NETWORK', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='network_description',
            field=models.TextField(default='Explore the locations of universities and companies participating in our platform.'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='network_title',
            field=models.CharField(default='Universities & Companies Across Uganda', max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='newsletter_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='privacy_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='site_name',
            field=models.CharField(default='InternConnect', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='student_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='tagline',
            field=models.CharField(default='Connect. Intern. Grow.', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='terms_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='university_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='x_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
