# Generated by Django 6.1.1 on 2026-10-05 04:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_landingpagesettings_about_video_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagesettings',
            name='about_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_image'),
        ),
        migrations.AlterField(
            model_name='landingpagesettings',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image'),
        ),
        migrations.AlterField(
            model_name='landingpagesettings',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
